-- ============================================================
-- LabControl - Script de criação do banco MySQL
-- Migração do sistema Delphi 7 + Firebird (DBMAIS.FDB)
-- ============================================================

CREATE DATABASE IF NOT EXISTS labcontrol
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE labcontrol;

-- ============================================================
-- SEGURANÇA
-- ============================================================

CREATE TABLE IF NOT EXISTS EMPRESAS (
    ID_EMPRESAS     INT AUTO_INCREMENT PRIMARY KEY,
    COD_EMPRESAS    VARCHAR(10) NOT NULL,
    ID_ENTIDADES    INT NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
    USUCOD      INT AUTO_INCREMENT PRIMARY KEY,
    USUNOM      VARCHAR(80) NOT NULL,
    USUSEN      VARCHAR(100) NOT NULL,
    USUADM      TINYINT(1) DEFAULT 0,
    INATIVO     TINYINT(1) DEFAULT 0,
    ID_ENTIDADES INT NULL
);

CREATE TABLE IF NOT EXISTS ACOES (
    USUCOD      INT NOT NULL,
    FORM        VARCHAR(50) NOT NULL,
    INCLUIR     TINYINT(1) DEFAULT 0,
    ALTERAR     TINYINT(1) DEFAULT 0,
    CONSULTAR   TINYINT(1) DEFAULT 0,
    EXCLUIR     TINYINT(1) DEFAULT 0,
    IMPRIMIR    TINYINT(1) DEFAULT 0,
    PRIMARY KEY (USUCOD, FORM),
    FOREIGN KEY (USUCOD) REFERENCES USUARIO(USUCOD)
);

-- ============================================================
-- ENTIDADES (Clientes, Funcionários, Fornecedores)
-- ============================================================

CREATE TABLE IF NOT EXISTS ENTIDADES (
    ID_ENTIDADES        INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA           CHAR(1) NOT NULL DEFAULT 'F' COMMENT 'F=PF, J=PJ',
    DATA_CADASTRO       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NOME                VARCHAR(150) NOT NULL,
    INATIVO             TINYINT(1) DEFAULT 0,
    TIPO_CLIENTE        TINYINT(1) DEFAULT 0,
    TIPO_FORNECEDOR     TINYINT(1) DEFAULT 0,
    TIPO_VENDEDOR       TINYINT(1) DEFAULT 0,
    TIPO_FUNCIONARIO    TINYINT(1) DEFAULT 0,
    TIPO_EMPRESA_USUARIA TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ENTIDADES_PF (
    ID_ENTIDADES    INT PRIMARY KEY,
    CPF             VARCHAR(14) NULL,
    NOME            VARCHAR(100) NOT NULL,
    SOBRENOME       VARCHAR(100) NULL,
    SEXO            CHAR(1) NULL COMMENT 'M=Masculino, F=Feminino',
    DATA_NASCIMENTO DATE NULL,
    RG              VARCHAR(20) NULL,
    ESTADO_CIVIL    CHAR(1) NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ENTIDADES_PJ (
    ID_ENTIDADES        INT PRIMARY KEY,
    CNPJ                VARCHAR(18) NULL,
    NOME_FANTASIA       VARCHAR(150) NULL,
    INSC_ESTADUAL       VARCHAR(30) NULL,
    INSC_MUNICIPAL      VARCHAR(30) NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIPOS_REG_PROFISSIONAL (
    ID_TIPOS_REG_PROFISSIONAL   INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO_REG_PROFISSIONAL  VARCHAR(50) NOT NULL COMMENT 'CRM, CRQ, etc.'
);

CREATE TABLE IF NOT EXISTS ENTIDADES_FUNCIONARIOS (
    ID_ENTIDADES                INT PRIMARY KEY,
    ID_TIPOS_REG_PROFISSIONAL   INT NULL,
    NR_REGISTRO_PROFISSIONAL    VARCHAR(30) NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE,
    FOREIGN KEY (ID_TIPOS_REG_PROFISSIONAL) REFERENCES TIPOS_REG_PROFISSIONAL(ID_TIPOS_REG_PROFISSIONAL)
);

CREATE TABLE IF NOT EXISTS ENDERECOS_TIPOS (
    ID_ENDERECOS_TIPOS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FONES_TIPOS (
    ID_FONES_TIPOS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO       VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENTIDADES_ENDERECOS (
    ID_ENTIDADES_ENDERECOS  INT AUTO_INCREMENT PRIMARY KEY,
    ID_ENTIDADES            INT NOT NULL,
    ID_ENDERECOS_TIPOS      INT NULL,
    LOGRADOURO              VARCHAR(150) NULL,
    NUMERO                  VARCHAR(10) NULL,
    COMPLEMENTO             VARCHAR(60) NULL,
    BAIRRO                  VARCHAR(80) NULL,
    CIDADE                  VARCHAR(80) NULL,
    UF                      CHAR(2) NULL,
    CEP                     VARCHAR(9) NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE,
    FOREIGN KEY (ID_ENDERECOS_TIPOS) REFERENCES ENDERECOS_TIPOS(ID_ENDERECOS_TIPOS)
);

CREATE TABLE IF NOT EXISTS ENTIDADES_FONES (
    ID_ENTIDADES_FONES  INT AUTO_INCREMENT PRIMARY KEY,
    ID_ENTIDADES        INT NOT NULL,
    ID_FONES_TIPOS      INT NULL,
    DDD                 VARCHAR(3) NULL,
    FONE                VARCHAR(15) NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE,
    FOREIGN KEY (ID_FONES_TIPOS) REFERENCES FONES_TIPOS(ID_FONES_TIPOS)
);

CREATE TABLE IF NOT EXISTS ENTIDADES_EMAILS (
    ID_ENTIDADES_EMAILS INT AUTO_INCREMENT PRIMARY KEY,
    ID_ENTIDADES        INT NOT NULL,
    PRINCIPAL           TINYINT(1) DEFAULT 0,
    EMAIL               VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES) ON DELETE CASCADE
);

-- ============================================================
-- TABELAS AUXILIARES DO LABORATÓRIO
-- ============================================================

CREATE TABLE IF NOT EXISTS AMOSTRAS_TIPO (
    ID_AMOSTRAS_TIPO    INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS AMOSTRAS_STATUS (
    ID_AMOSTRAS_STATUS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL,
    COR                 VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS ANALISES_TIPO (
    ID_ANALISES_TIPO    INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS ANALISES_STATUS (
    ID_ANALISES_STATUS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL,
    COR                 VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS ANALISES_METODOS (
    ID_ANALISES_METODOS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOLETINS_STATUS (
    ID_BOLETINS_STATUS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL,
    COR                 VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS IDIOMAS (
    ID_IDIOMAS  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO   VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRAZOS (
    ID_PRAZOS   INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO   VARCHAR(80) NOT NULL,
    QTDE        INT NOT NULL COMMENT 'Quantidade em dias'
);

CREATE TABLE IF NOT EXISTS MOEDAS (
    ID_MOEDAS   INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO   VARCHAR(50) NOT NULL,
    SIGLA       VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS UNIDADES (
    ID_UNIDADES INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO   VARCHAR(50) NOT NULL,
    SIGLA       VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMBALAGENS_TIPOS (
    ID_EMBALAGENS_TIPOS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO           VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS LAB_PROPOSTAS_STATUS (
    ID_LAB_PROPOSTAS_STATUS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO               VARCHAR(80) NOT NULL,
    COR                     VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS LAB_TIPOS_RESULTADOS (
    ID_LAB_TIPOS_RESULTADOS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO               VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONDICOES_PAGTOS (
    ID_CONDICOES_PAGTOS INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO              VARCHAR(10) NOT NULL,
    DESCRICAO           VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PRODUTOS         INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO              VARCHAR(20) NOT NULL UNIQUE,
    DESCRICAO           VARCHAR(150) NOT NULL,
    ID_UNIDADES         INT NULL,
    ID_EMBALAGENS_TIPOS INT NULL,
    QTDE_EMBALAGEM      DECIMAL(15,4) NULL,
    FOREIGN KEY (ID_UNIDADES) REFERENCES UNIDADES(ID_UNIDADES),
    FOREIGN KEY (ID_EMBALAGENS_TIPOS) REFERENCES EMBALAGENS_TIPOS(ID_EMBALAGENS_TIPOS)
);

CREATE TABLE IF NOT EXISTS LAB_PARAMETROS_ANALISES (
    ID_LAB_PARAMETROS_ANALISES  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO                   VARCHAR(150) NOT NULL,
    ID_ANALISES_TIPO            INT NULL,
    VR_UNITARIO                 DECIMAL(15,4) NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_ANALISES_TIPO) REFERENCES ANALISES_TIPO(ID_ANALISES_TIPO)
);

-- ============================================================
-- PROPOSTAS
-- ============================================================

CREATE TABLE IF NOT EXISTS LAB_PROPOSTAS (
    ID_LAB_PROPOSTAS        INT AUTO_INCREMENT PRIMARY KEY,
    ID_ENTIDADES            INT NOT NULL,
    ID_EMPRESAS             INT NOT NULL,
    COD_PROPOSTA            INT NOT NULL,
    ANO_PROPOSTA            INT NOT NULL,
    REV_PROPOSTA            INT NOT NULL DEFAULT 0,
    DT_SOLICITACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_VALIDADE             DATE NULL,
    ID_LAB_PROPOSTAS_STATUS INT NULL,
    VR_TOTAL_PROPOSTA       DECIMAL(15,4) NOT NULL DEFAULT 0,
    PORC_DESCONTO           DECIMAL(5,2) NULL,
    VR_DESCONTO             DECIMAL(15,4) NULL,
    ID_ENTIDADES_FUNC       INT NULL,
    ID_CONDICOES_PAGTOS     INT NULL,
    DT_AUTORIZACAO          DATETIME NULL,
    ID_MOEDAS               INT NULL,
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES),
    FOREIGN KEY (ID_LAB_PROPOSTAS_STATUS) REFERENCES LAB_PROPOSTAS_STATUS(ID_LAB_PROPOSTAS_STATUS),
    FOREIGN KEY (ID_CONDICOES_PAGTOS) REFERENCES CONDICOES_PAGTOS(ID_CONDICOES_PAGTOS),
    FOREIGN KEY (ID_MOEDAS) REFERENCES MOEDAS(ID_MOEDAS)
);

CREATE TABLE IF NOT EXISTS LAB_PROPOSTAS_ANALISES (
    ID_LAB_PROPOSTAS_ANALISES   INT AUTO_INCREMENT PRIMARY KEY,
    ID_LAB_PROPOSTAS            INT NOT NULL,
    ID_PRODUTOS                 INT NULL,
    ID_ANALISES_METODOS         INT NULL,
    ID_ANALISES_TIPO            INT NULL,
    ID_LAB_PARAMETROS_ANALISES  INT NULL,
    ID_IDIOMAS                  INT NULL,
    QTDE_AMOSTRAS               INT NOT NULL DEFAULT 1,
    VR_UNITARIO                 DECIMAL(15,4) NOT NULL DEFAULT 0,
    VR_DESCONTO                 DECIMAL(15,4) NOT NULL DEFAULT 0,
    VR_TOTAL                    DECIMAL(15,4) NOT NULL DEFAULT 0,
    ID_PRAZOS                   INT NULL,
    FOREIGN KEY (ID_LAB_PROPOSTAS) REFERENCES LAB_PROPOSTAS(ID_LAB_PROPOSTAS) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS),
    FOREIGN KEY (ID_ANALISES_METODOS) REFERENCES ANALISES_METODOS(ID_ANALISES_METODOS),
    FOREIGN KEY (ID_ANALISES_TIPO) REFERENCES ANALISES_TIPO(ID_ANALISES_TIPO),
    FOREIGN KEY (ID_PRAZOS) REFERENCES PRAZOS(ID_PRAZOS)
);

-- ============================================================
-- AMOSTRAS
-- ============================================================

CREATE TABLE IF NOT EXISTS LAB_HIST_AMOSTRAS (
    ID_LAB_HIST_AMOSTRAS        INT AUTO_INCREMENT PRIMARY KEY,
    ID_AMOSTRAS_TIPO            INT NOT NULL,
    COD_AMOSTRA                 INT NOT NULL,
    ID_ANALISES_TIPO            INT NULL,
    ANO_AMOSTRA                 INT NOT NULL,
    ID_ENTIDADES                INT NULL,
    NOME_CONTATO                VARCHAR(100) NULL,
    ID_LAB_PROPOSTAS            INT NULL,
    DT_ENTREGA                  DATETIME NULL,
    HR_ENTREGA                  VARCHAR(5) NULL,
    LOCAL_RECEBIMENTO           VARCHAR(100) NULL,
    ID_EMBALAGENS_TIPOS         INT NULL,
    QTDE_EMBALAGENS_ENTREGUE    INT NULL,
    ID_PRODUTOS                 INT NULL,
    NR_LOTE                     VARCHAR(50) NULL,
    DT_FABRICACAO               DATE NULL,
    DT_VALIDADE                 DATE NULL,
    NOTA_ROTULO                 VARCHAR(100) NULL,
    ESPECIE_AMOSTRA             VARCHAR(100) NULL,
    ASPECTO_AMOSTRA             VARCHAR(100) NULL,
    COR                         VARCHAR(50) NULL,
    OUTRAS_CARACTERISTICAS      VARCHAR(200) NULL,
    QTDE_AMOSTRA_VERIFICACAO    DECIMAL(15,4) NULL,
    TEMPERATURA_VERIFICACAO     DECIMAL(5,2) NULL,
    ACOMPANHA_FICHA_TECNICA     TINYINT(1) DEFAULT 0,
    ACOMPANHA_PADRAO_ANALITICO  TINYINT(1) DEFAULT 0,
    ACOMPANHA_CA_CLIENTE        TINYINT(1) DEFAULT 0,
    ENVIAR_OUTRO_LABORATORIO    TINYINT(1) DEFAULT 0,
    QTDE_ENVIO_OUTRO_LABORATORIO INT NULL,
    ID_AMOSTRAS_STATUS          INT NULL,
    ID_ENTIDADES_FUNC_DIG       INT NULL,
    ID_EMPRESAS                 INT NOT NULL,
    FOREIGN KEY (ID_AMOSTRAS_TIPO) REFERENCES AMOSTRAS_TIPO(ID_AMOSTRAS_TIPO),
    FOREIGN KEY (ID_ANALISES_TIPO) REFERENCES ANALISES_TIPO(ID_ANALISES_TIPO),
    FOREIGN KEY (ID_ENTIDADES) REFERENCES ENTIDADES(ID_ENTIDADES),
    FOREIGN KEY (ID_LAB_PROPOSTAS) REFERENCES LAB_PROPOSTAS(ID_LAB_PROPOSTAS),
    FOREIGN KEY (ID_EMBALAGENS_TIPOS) REFERENCES EMBALAGENS_TIPOS(ID_EMBALAGENS_TIPOS),
    FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID_PRODUTOS),
    FOREIGN KEY (ID_AMOSTRAS_STATUS) REFERENCES AMOSTRAS_STATUS(ID_AMOSTRAS_STATUS)
);

CREATE TABLE IF NOT EXISTS LAB_HIST_AMOSTRAS_TESTES (
    ID_LAB_HIST_AMOSTRAS_TESTES INT AUTO_INCREMENT PRIMARY KEY,
    ID_LAB_HIST_AMOSTRAS        INT NOT NULL,
    ID_ANALISES_TIPO            INT NULL,
    ID_ANALISES_METODOS         INT NULL,
    ID_IDIOMAS                  INT NULL,
    ID_PRAZOS                   INT NULL,
    ID_ENTIDADES                INT NULL,
    ID_LAB_PARAMETROS_ANALISES  INT NULL,
    FOREIGN KEY (ID_LAB_HIST_AMOSTRAS) REFERENCES LAB_HIST_AMOSTRAS(ID_LAB_HIST_AMOSTRAS) ON DELETE CASCADE,
    FOREIGN KEY (ID_ANALISES_TIPO) REFERENCES ANALISES_TIPO(ID_ANALISES_TIPO),
    FOREIGN KEY (ID_ANALISES_METODOS) REFERENCES ANALISES_METODOS(ID_ANALISES_METODOS),
    FOREIGN KEY (ID_PRAZOS) REFERENCES PRAZOS(ID_PRAZOS)
);

CREATE TABLE IF NOT EXISTS LAB_HIST_AMOSTRAS_SALDO (
    ID_LAB_HIST_AMOSTRAS    INT PRIMARY KEY,
    ID_EMPRESAS             INT NOT NULL,
    SALDO_ATUAL             DECIMAL(15,4) NOT NULL DEFAULT 0,
    DATA_ATUALIZACAO        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_LAB_HIST_AMOSTRAS) REFERENCES LAB_HIST_AMOSTRAS(ID_LAB_HIST_AMOSTRAS) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LAB_MOV_AMOSTRAS (
    ID_LAB_MOV_AMOSTRAS     INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESAS             INT NOT NULL,
    ID_LAB_HIST_AMOSTRAS    INT NOT NULL,
    ID_ENTIDADES_FUNC       INT NULL,
    DATA_MOV                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QTDE                    DECIMAL(15,4) NOT NULL,
    E_S                     CHAR(1) NOT NULL COMMENT 'E=Entrada, S=Saída',
    JUSTIFICATIVA           VARCHAR(200) NULL,
    AMOSTRA_COMPLEMENTAR    TINYINT(1) DEFAULT 0,
    FOREIGN KEY (ID_LAB_HIST_AMOSTRAS) REFERENCES LAB_HIST_AMOSTRAS(ID_LAB_HIST_AMOSTRAS)
);

CREATE TABLE IF NOT EXISTS LAB_LOCAL_AMOSTRAS (
    ID_LAB_LOCAL_AMOSTRAS   INT AUTO_INCREMENT PRIMARY KEY,
    ID_LAB_HIST_AMOSTRAS    INT NOT NULL UNIQUE,
    ID_EMPRESAS             INT NOT NULL,
    LOCAL                   VARCHAR(100) NULL,
    ID_FUNCIONARIO_DESCARTE INT NULL,
    DT_HR_DESCARTE          DATETIME NULL,
    FOREIGN KEY (ID_LAB_HIST_AMOSTRAS) REFERENCES LAB_HIST_AMOSTRAS(ID_LAB_HIST_AMOSTRAS) ON DELETE CASCADE
);

-- ============================================================
-- RESULTADOS
-- ============================================================

CREATE TABLE IF NOT EXISTS LAB_RESULTADOS_ANALISES (
    ID_LAB_RESULTADOS_ANALISES  INT AUTO_INCREMENT PRIMARY KEY,
    ID_LAB_HIST_AMOSTRAS        INT NOT NULL,
    ID_ENTIDADES_FUNC_DIG       INT NULL,
    ID_EMPRESAS                 INT NOT NULL,
    REVISAO                     INT NOT NULL DEFAULT 0,
    DT_RESULTADO                DATETIME NULL,
    FOREIGN KEY (ID_LAB_HIST_AMOSTRAS) REFERENCES LAB_HIST_AMOSTRAS(ID_LAB_HIST_AMOSTRAS)
);

CREATE TABLE IF NOT EXISTS LAB_RESULTADOS_PARAM (
    ID_LAB_RESULTADOS_PARAM         INT AUTO_INCREMENT PRIMARY KEY,
    ID_LAB_RESULTADOS_ANALISES      INT NOT NULL,
    ID_LAB_HIST_AMOSTRAS_TESTES     INT NULL,
    DT_RESULTADO                    DATETIME NULL,
    TIPO_RESULTADO                  CHAR(1) NULL COMMENT 'N=Numérico, S=Satisfeito/Insatisfeito, E=Especial',
    ID_UNIDADES                     INT NULL,
    VR_SATISFEITO                   TINYINT(1) NULL,
    ID_ENTIDADES_FUNC_ANALISE       INT NULL,
    QT_AMOSTRA                      DECIMAL(15,4) NULL,
    VR_RESULTADO                    VARCHAR(100) NULL,
    VR_RESULTADO_ESPECIF            VARCHAR(100) NULL,
    SIMBOLO_GRANDEZA                VARCHAR(20) NULL,
    FOREIGN KEY (ID_LAB_RESULTADOS_ANALISES) REFERENCES LAB_RESULTADOS_ANALISES(ID_LAB_RESULTADOS_ANALISES) ON DELETE CASCADE,
    FOREIGN KEY (ID_UNIDADES) REFERENCES UNIDADES(ID_UNIDADES)
);

-- ============================================================
-- TRIGGER: atualiza saldo ao inserir movimentação
-- ============================================================

DELIMITER $$

CREATE TRIGGER IF NOT EXISTS TRG_MOV_AMOSTRAS_AI
AFTER INSERT ON LAB_MOV_AMOSTRAS
FOR EACH ROW
BEGIN
    IF NEW.E_S = 'E' THEN
        UPDATE LAB_HIST_AMOSTRAS_SALDO
           SET SALDO_ATUAL = SALDO_ATUAL + NEW.QTDE,
               DATA_ATUALIZACAO = NOW()
         WHERE ID_LAB_HIST_AMOSTRAS = NEW.ID_LAB_HIST_AMOSTRAS;
    ELSE
        UPDATE LAB_HIST_AMOSTRAS_SALDO
           SET SALDO_ATUAL = SALDO_ATUAL - NEW.QTDE,
               DATA_ATUALIZACAO = NOW()
         WHERE ID_LAB_HIST_AMOSTRAS = NEW.ID_LAB_HIST_AMOSTRAS;
    END IF;
END$$

DELIMITER ;

-- ============================================================
-- DADOS INICIAIS
-- ============================================================

INSERT INTO ENDERECOS_TIPOS (DESCRICAO) VALUES ('Nota Fiscal'), ('Correspondência'), ('Entrega'), ('Cobrança');
INSERT INTO FONES_TIPOS (DESCRICAO) VALUES ('Comercial'), ('Residencial'), ('Celular'), ('Fax');
INSERT INTO MOEDAS (DESCRICAO, SIGLA) VALUES ('Real', 'BRL'), ('Dólar', 'USD'), ('Euro', 'EUR');
INSERT INTO AMOSTRAS_STATUS (DESCRICAO, COR) VALUES ('Aguardando', '#FFC107'), ('Em Análise', '#17A2B8'), ('Concluído', '#28A745'), ('Cancelado', '#DC3545');
INSERT INTO BOLETINS_STATUS (DESCRICAO, COR) VALUES ('Em elaboração', '#FFC107'), ('Emitido', '#28A745'), ('Cancelado', '#DC3545');
INSERT INTO LAB_PROPOSTAS_STATUS (DESCRICAO, COR) VALUES ('Em elaboração', '#FFC107'), ('Enviada', '#17A2B8'), ('Aprovada', '#28A745'), ('Cancelada', '#DC3545');
INSERT INTO IDIOMAS (DESCRICAO) VALUES ('Português'), ('Inglês'), ('Espanhol');
INSERT INTO EMPRESAS (COD_EMPRESAS, ID_ENTIDADES) VALUES ('001', 1);

-- Usuário admin padrão (senha: admin123 - trocar após primeiro login)
INSERT INTO ENTIDADES (CATEGORIA, NOME) VALUES ('F', 'Administrador');
INSERT INTO USUARIO (USUNOM, USUSEN, USUADM) VALUES ('admin', SHA2('admin123', 256), 1);
